### PR TITLE
Dockerfiles for each php version

### PR DESCRIPTION
**Pull request by winfried-van-loon**
This is to improve how workspace handles the different PHP versions. I've mostly copied it from the other files. 

**Before merging**, these files must be tested. I'm not sure how to use Laradock with a base image that's not on Docker Hub.

This should solve #8 and will make fixes available for several issues in the laradock/laradock repo.

### CODE REVIEW

**Comment by jcoetsie** [comment]
Hi,

Why not base the workspace on the official php container like in the php-fpm?

**Comment by Mahmoudz** [comment]
@jcoetsie I'm gonna rephrase your question to make sure I got it right, you're asking why not using the `php-fpm` container as workspace, and just execute our commands from there!? 

If that's the question: the answer is: unlike php-fpm, you won't need the workspace in production. So they must remain separate. 

Actually if it's possible to separate every single tool of the Workspace container to it's own container I would do it immediately. Cause the less software's running in a container the easier it becomes to maintain and the smaller to download and the faster to build... and no one needs all the tools anyway.

**Comment by mikeerickson** [comment]
@Mahmoudz I have considered this as well, but can't think of good solution to communicate between containers (such as access MySQL clip from other containers, run phpunit, run node tasks, etc)

**Comment by winfried-van-loon** [comment]
To test this image, should I just merge it, hope it gets picked up by Docker Hub and test it with laradock/laradock by locally changing the workspace version number?

I'm not quite familiar with base images.

**Comment by Dayjo** [comment]
@winfried-van-loon hmm, have you tried just manually overwriting the directory in the laradock folder and building?

**Comment by Mahmoudz** [comment]
@winfried-van-loon can we have the same result, without duplicated code, between different dockerfiles? Cause right now we're going toward having 6 dockerfiles just to support 3 php version (3 for base and 3 in laradock) in the same container and that's gonna be almost impossible to maintain, especially when new version are coming in the future!

Solution 1: Merging the common configurations in a base Image.

Solution 2: (most likely) single dockerfile, with multiple "if else" statements. If the let's say php 5.6 and php 7 have different configuration setup for the same tool, but php 7.0 and 7.1 have the same. We would add if php 5.6 do this.. else if 7.0 or 7.1 do that... 

Solution 3: Inheriting from other dockerfiles, just to load the different configurations required by each php version. Example the main dockerfile inherits from php7dockerfile or php6docker file..  (if this is possible with docker!).

What do you guys think!? and we can combine Solution 1 and 2 taking out the very common and unchanged configurations, to the base image to reduce the build time.

I'm open to hear your solutions as well.

**Comment by winfried-van-loon** [comment]
Great idea! I'll look into it when I've got the time.

**Comment by mikeerickson** [comment]
@Mahmoudz @winfried-van-loon I like the idea of Solution 3 and feel this would eventually run down to PHP 5.6 and PHP 7.1 (don't see a compelling reason in the long haul to support each .X revision)

As it stands, I need to get PHP 7.1 working (still having issues with that) . And, I have also seen that accessing PHP from within the workspace (why different versions)

PHP-FPM Container
``` 
PHP 7.0.9 (cli) (built: Aug 10 2016 19:45:48) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
root@7afc8e710017:/var/www#
```

Workspace Container
```
PHP 7.0.18-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 14:36:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by bestlong** [comment]
Hi @Mahmoudz Why not merge PR to new branch, and  push new docker image, set tag name like:

- laradock/workspace:x.x-php56-rc1
- laradock/workspace:x.x-php70-rc1
- laradock/workspace:x.x-php71-rc1

x.x is version number

so that we can start the manual test for laradock/laradock project.

**Comment by winfried-van-loon** [comment]
It's relatively easy to fix the if-else statements to merge the dockerfiles together to keep 1 or two. I hope to have the time to finish it this evening, about 12-13 hours from now. Could merge it, though. But it's a lot of (manual) testing if a new version of workspace is released tomorrow, we'll have to do the (manual) testing all over again.

**Comment by winfried-van-loon** [comment]
Alright, an midnight update: I'm currently merging the Docker files 70 and 71 together, will then look into merging 56 into there as well. Since I'm kind of new to a lot of the specific Docker commands, I had to do more research than I expected beforehand. I suggest to move the merge of the Dockerfiles into another pull request, so this one can be merged.

I tested the three Dockerfiles using the instructions @bestlong gave me, which worked perfectly. Other than nagging about the `debconf` warning, there were no issues. When Googling that warning, the explanations are really vague. One this is clear, it's not a really interesting warning, I suggest ignoring it for now as we've done till now :).

```
debconf: delaying package configuration, since apt-utils is not installed
```

**Comment by winfried-van-loon** [comment]
It was easier than expected when the research was done, made another pull request for the Dockerfile merge so this pull request can be completed.

**Pull request closed without merging**
